# config/packages/nelmio_cors.yaml
nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:3000']  # Replace with your frontend URL
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['http://localhost:3000']
